- name: Install required binary packages
  apt: name={{item}} state=installed
  with_items:
  - php-pear
  - python-pexpect

- name: Check if horde pear channel is installed
  shell: pear list-channels | grep pear.horde.org
  register: channel_registered
  failed_when: channel_registered.rc >= 2

- name: Discover horde PEAR channel
  command: pear channel-discover pear.horde.org
  when: channel_registered.stdout == ''

- name: Check if horde pear package is installed
  shell: pear list -c pear.horde.org | grep Horde_Role
  register: package_installed
  failed_when: package_installed.rc >= 2

- name: Install horde package
  command: pear install horde/horde_role
  when: package_installed.stdout == ''

- name: run scripts on horde package
  expect:
    command: pear run-scripts horde/horde_role
    responses:
      "Filesystem location for the base Horde application : ": "/usr/share/horde"

- name: Check if horde pear webmail is installed
  shell: pear list -c pear.horde.org | grep webmail
  register: webmail_package_installed
  failed_when: webmail_package_installed.rc >= 2

- name: Install horde webmail
  command: pear install -a -B horde/webmail
  when: webmail_package_installed.stdout == ''

- name: Finalize horde webmail install
  command: webmail-install
- name: run scripts on horde package
  expect:
    command: pear run-scripts horde/horde_role
    responses:
      Filesystem location for the base Horde application.*: /usr/share/horde
      What database backend should we use.*: "mysql"
      Username to connect to the database as.*: "{{ horde_db_user }}"
      Password to connect with.*: "{{ horde_db_password }}"
      How should we connect to the database.*: "tcp"
      Database server.*: "localhost"
      Port the DB is running on, if non-standard.*: "3306"
      Database name to use.*: "horde"
      Internally used charset.*: "utf-8"
      Use SSL to connect to the server.*: "false"
      Split reads to a different server.*: "false"
      Should Horde log all queries.*: "0"


- lineinfile:
    path: /etc/apache2.conf
    state: present
    regexp: '^AcceptPathInfo'
    line: 'AcceptPathInfo On'

