---
- name: setup Postfix custom configuration
  template: src=postfix-main.cf.j2 dest=/etc/postfix/main.cf
  notify: restart postfix
  
- name: Creating directory for MySQL mappings.
  file: path=/etc/postfix/mysql mode=0644 state=directory

- name: define Postfix relay domains
  template: src=postfix-mysql-relay_domains.cf.j2 dest=/etc/postfix/mysql/relay_domains.cf
  notify: restart postfix

- name: define Postfix virtual alias mapping
  template: src=postfix-mysql-virtual_alias_maps.cf.j2 dest=/etc/postfix/mysql/virtual_alias_maps.cf
  notify: restart postfix

- name: define Postfix virtual domains mapping
  template: src=postfix-mysql-virtual_domains_maps.cf.j2 dest=/etc/postfix/mysql/virtual_domains_maps.cf
  notify: restart postfix

- name: define Postfix virtual alias mapping
  template: src=postfix-mysql-virtual_mailbox_maps.cf.j2 dest=/etc/postfix/mysql/virtual_mailbox_maps.cf
  notify: restart postfix

- name: Restricting access to database mapping files that contain a password
  file: path=/etc/postfix/mysql/{{item}}.cf mode=0644 owner=root group=root
  with_items:
  - relay_domains
  - virtual_alias_maps
  - virtual_domains_maps
  - virtual_mailbox_maps

- name: Ensuring rights are correctly set in postfix config
  file:
    path: /etc/postfix
    mode: 0755
    recurse: yes

- name: Define spamassassin config
  template: src=etc-default-spamassassin.j2 dest=/etc/default/spamassassin
  notify: restart spamassassin

- name: Adding user spamass-milter to debian-spamd group
  user: name=spamass-milter groups=debian-spamd
  notify: restart spamassassin
