- name: Install required binary packages
  apt: name={{item}} state=installed
  with_items:
  - php-pear
  - python-pexpect

- name: Check if horde pear channel is installed
  shell: pear list-channels | grep pear.horde.org
  register: channel_registered
  failed_when: channel_registered.rc >= 2

- name: Discover horde PEAR channel
  command: pear channel-discover pear.horde.org
  when: channel_registered.stdout == ''

- name: Check if horde pear package is installed
  shell: pear list -c pear.horde.org | grep Horde_Role
  register: package_installed
  failed_when: package_installed.rc >= 2

- name: Install horde package
  command: pear install horde/horde_role
  when: package_installed.stdout == ''

- name: Generating expct setup scripts
  template:
    src: "{{ item }}.sh.j2"
    dest: "/tmp/{{ item }}.sh"
    mode: "+x"
  with_items:
    - horde-run-script
    - webmail_install-script

- name: Run scripts on horde package
  command: /tmp/horde-run-script.sh

- name: Check if horde pear webmail is installed
  shell: pear list -c pear.horde.org | grep webmail
  register: webmail_package_installed
  failed_when: webmail_package_installed.rc >= 2

- name: Install horde webmail
  command: pear install -a -B horde/webmail
  when: webmail_package_installed.stdout == ''

- name: Finalize horde webmail install
  command: /tmp/webmail_install-script.sh
  become: true

- lineinfile:
    path: /etc/apache2/apache2.conf
    state: present
    regexp: '^AcceptPathInfo'
    line: 'AcceptPathInfo On'

- name: Copying horde web config
  copy:
    src: horde.conf
    dest: /etc/apache2/conf-available/horde.conf

- name: configuring horde to use postfixadmin accounts.
  template:
    src: horde-password-backend.php.j2
    dest: /usr/share/php/www/horde/config/backends.php
  notify: restart apache
    
- name: configuring horde to use postfixadmin accounts.
  template:
    src: horde-conf.local.php.j2
    dest: /usr/share/php/www/horde/config/conf.local.php
  notify: restart apache

- name: Removing config from mnemos element which breaks horde.
  file:
    path: /usr/share/php/www/horde/mnemo/config/conf.php 
    state: absent
  notify: restart apache

- name: Enabling horde web config
  command: a2enconf horde
  notify: restart apache
