---
- name: Installing required Python mysqldb module for Ansible to manage databases
  apt: pkg=python-mysqldb state=installed
# - name: Creating my-cnf for root user
#   template: src=root-my-cnf.j2 dest=/root/.my.cnf mode=0600
- name: set the MySQL root user's password
  mysql_user: name=root password={{ispmail_mysql_root_password}} state=present
  ignore_errors: yes
#~ - name: creating mailserver MySQL database
  #~ mysql_db: name=mailserver state=present login_user=root login_password={{ispmail_mysql_root_password}}
#~ - name: creating Roundcube MySQL database
  #~ mysql_db: name=roundcube state=present login_user=root login_password={{ispmail_mysql_root_password}}
- name: creating Postfixadmin MySQL database
  mysql_db: name=postfixadmin state=present login_user=root login_password={{ispmail_mysql_root_password}}
#~ - name: copying MySQL database schema to server
  #~ copy: src=schema.sql dest=/tmp
#~ - name: setting up SQL schema of mailserver database
  #~ mysql_db: name=mailserver state=import target=/tmp/schema.sql login_user=root login_password={{ispmail_mysql_root_password}}
#~ - name: copying MySQL database schema to server
  #~ copy: src=postfixadmin.sql dest=/tmp
#~ - name: setting up SQL schema of postfixadmin database
  #~ mysql_db: name=postfixadmin state=import target=/tmp/postfixadmin.sql login_user=root login_password={{ispmail_mysql_root_password}}

# - name: set the MySQL root user's password
  # mysql_user: name=root password={{ispmail_mysql_root_password}} state=present
#~ - name: creating MySQL user to read the mailserver database
  #~ mysql_user: name=mailuser password={{ispmail_mysql_mailuser_password}} priv=mailserver.*:SELECT,INSERT,UPDATE,DELETE state=present login_user=root login_password={{ispmail_mysql_root_password}}
- name: creating MySQL user to read the postfixadmin database
  mysql_user: name=postfixadmin password={{ispmail_mysql_mailuser_password}} priv=postfixadmin.*:ALL state=present login_user=root login_password={{ispmail_mysql_root_password}}
#~ - name: creating MySQL user for roundcube
  #~ mysql_user: name=roundcube password={{ispmail_mysql_roundcube_password}} priv=roundcube.*:ALL state=present login_user=root login_password={{ispmail_mysql_root_password}}
#~ - name: copying MySQL test data to server
  #~ copy: src=test.sql dest=/tmp
  #~ when: ispmail_populate_test_data == true
#~ - name: populating the database with test data
  #~ mysql_db: name=mailserver state=import target=/tmp/test.sql login_user=root login_password={{ispmail_mysql_root_password}}
  #~ when: ispmail_populate_test_data == true
#~ - name: Intitializing roundcube database if needed.
  #~ mysql_db: name=roundcube state=import target=/usr/share/roundcube/SQL/mysql.initial.sql login_user=root login_password={{ispmail_mysql_root_password}}
  #~ ignore_errors: yes
# - name: Create root's .my.cnf
#   template: src=my-cnf.j2 dest=/root/.my.cnf mode=0600
