---
- name: Installing required Python mysqldb module for Ansible to manage databases
  apt: pkg=python-mysqldb state=installed
- name: set the MySQL root user's password
  mysql_user: name=root password={{ispmail_mysql_root_password}} state=present
  ignore_errors: yes
- name: creating Postfixadmin MySQL database
  mysql_db: name=postfixadmin state=present login_user=root login_password={{ispmail_mysql_root_password}}
- name: creating MySQL user to read the postfixadmin database
  mysql_user: name=postfixadmin password={{ispmail_mysql_mailuser_password}} priv=postfixadmin.*:ALL state=present login_user=root login_password={{ispmail_mysql_root_password}}
