- name: Install prerequisites for roundcube
  tags: ispmail-packages
  include_tasks: ispmail-packages.yml
  
- name: Install certificate
  tags: ispmail-certificate
  include_tasks: ispmail-certificate.yml
  
- name: Setup database for postfixadmin
  tags: ispmail-database
  include_tasks: ispmail-database.yml
  
- name: Setup postfix for roundcube
  tags: ispmail-postfix
  include_tasks: ispmail-postfix.yml
  
- name: Setup postfixadmin
  tags: ispmail-postfixadmin
  include_tasks: ispmail-postfixadmin.yml
