# This is the main ansible-playbook

# Run using:
# ansible-playbook site.yml -i environments/vm/inventory

- name: Configuration for all nodes
  hosts: all
  become: yes
  tags: common
  gather_facts: no
  remote_user: "{{ ansible_remote_user }}"

  roles:
  - common


# Applies the "mua" role to hosts belonging the the webmail group.
- name: Apply role "mua" to hosts in group "webmail"
  hosts: webmail
  become: yes
  tags: mua
  gather_facts: no
  remote_user: "{{ ansible_remote_user }}"

  roles:
  - mua
